### ISSUE TITLE
补充：请支持EWE全球快递的单号

### ISSUE THREAD

**Issue by mapleshadow** [fython/PackageTracker#12]
RT，感谢，他的网址是：
https://www.ewe.com.au/
内部应该有接口说明之类把，还请支持感谢！
PS：很多澳大利亚奶粉都是这个快递公司，我相信用的人肯定多

**Comment by coderfox** [comment]
可否提供一个示例单号？

**Comment by coderfox** [comment]
This issue relates to the Pinyin lib `com.spreada.utils.chinese.ZHConverter`.

All express companies starting with English cannot be searched.

Currently you may try searching `全球快递` and select it.

Actually it is supported.
