### ISSUE TITLE
添加单个快递刷新

### ISSUE THREAD

**Issue by WanderMax** [fython/PackageTracker#19]
发现多个快递时候, 刷新有时候不能更新
能否加入 打开一个快递条目, 下拉刷新此快递单号的特性?

**Comment by lmy441900** [comment]
> 能否加入 打开一个快递条目, 下拉刷新此快递单号的特性?

我也觉得是。

**Comment by WanderMax** [comment]
多个快递 经常更新失败!!!

**Comment by coderfox** [comment]
Implemented. You may close it.
