### ISSUE TITLE
7.1从快捷方式添加无效

### ISSUE THREAD

**Issue by tyan-boot** [fython/PackageTracker#21]
从长按快捷方式选择手动添加，输入EMS号之后选择强制添加EMS，下一步输入名称之后按下一步添加不进去。

**Comment by coderfox** [comment]
无法复现，请提供样例单号。

**Comment by fython** [comment]
在 26b79c491264cc0466cf475465b2c5cb3f36a619 提交中应该已经修复了各个系统版本上的添加无效问题，暂时先关闭 issue。
