### ISSUE TITLE
Incorrect location display on BaiShi Express packages

### ISSUE THREAD

**Issue by coderfox** [fython/PackageTracker#26]
Though the information is given correctly, the details page gives out a corrupted text and no location is displayed.
I suggest a fix and a switch of this feature.
![result-2017-01-02-09-21-06](https://cloud.githubusercontent.com/assets/3616727/21583838/ce9867b2-d057-11e6-8161-09968be424ea.png)
![screenshot_20170102-092035](https://cloud.githubusercontent.com/assets/3616727/21583841/d5899f1e-d057-11e6-96f2-ae357bb0acdb.png)

**Comment by fython** [comment]
Okay. I will fix it.

**Comment by coderfox** [comment]
I forgot to attach a package code.
70117838466930 . This is the code of the package in the picture.

**Comment by ArchieMeng** [comment]
@coderfox Bug fixed.I have release a beta version apk in my forked repository .Please have a try.
https://github.com/ArchieMeng/PackageTracker
