### ISSUE TITLE
Suggestion: detect Package number in the clipboard

### ISSUE THREAD

**Issue by ArchieMeng** [fython/PackageTracker#36]
There are lots of times that user will copy package number from JD, TAOBAO or other apps.
 So how about detect package number from clipboard by ClipboardManager? On this way, no permission is required.

**Comment by fython** [comment]
Is it possible to receive a clipboard event in background? Seems Google Translate can work well. Maybe it's a good idea.

**Comment by ArchieMeng** [comment]
It seems possible.
I found this.
https://stackoverflow.com/questions/19963785/service-android-clipboard-listener
