### ISSUE TITLE
使用联通数据流量时出现 非法访问:IP禁止访问

### ISSUE THREAD

**Issue by mo10** [fython/PackageTracker#37]
使用联通数据流量时出现 非法访问:IP禁止访问 ，并且无法拉取包裹新动态
用wifi就没有这样的问题，API有屏蔽措施？
![screenshot_20170626-015159](https://user-images.githubusercontent.com/9402279/27518444-f4a7b1b0-59a5-11e7-979f-610953c8257e.png)

**Comment by fython** [comment]
API 是由快递 100 提供的，暂时想不到什么解决办法。即便用一个服务器做中转使用频率上去了可能也会被屏蔽。

**Comment by mo10** [comment]
以前分析了一个百度的查询接口(也是快递100提供的数据)https://github.com/mo10/Baidu-Express-Query
不知是否有帮助

**Comment by fython** [comment]
感谢提供另一个接口，关于多 API 支持我开了一个新 issue。 #38
