### ISSUE TITLE
将搜索和添加快递分离

### ISSUE THREAD

**Issue by eastmalon** [fython/PackageTracker#43]
建议增加一个浮动按钮来添加快递，而不是在搜索中添加快递。
原来的设计既不方便也不符合规范，在大多数md设计的软件中搜索和添加都是分开的。

**Comment by vadonmo** [comment]
你看看拨号是哪样的

**Comment by eastmalon** [comment]
这跟拨号不能一并而论吧，应该和通讯录比较。

**Comment by vadonmo** [comment]
不一样么，你得通讯录不是搜索添加一块的吗

**Comment by eastmalon** [comment]
Google的通讯录不是一块的。
https://play.google.com/store/apps/details?id=com.google.android.contacts

**Comment by lmy441900** [comment]
原设计的单独的添加按钮在使用上会更直观一点。

**Comment by fython** [comment]
未来的正式版本将会重新设计首页，感谢各位的反馈和支持。
