### ISSUE TITLE
A Suggestion

### ISSUE THREAD

**Issue by jianhui1012** [fython/PackageTracker#45]
For convenience,place QR code to download the app,push the apk the Application hosting platform,such as [pgyer](https://www.pgyer.com/),[fir](https://fir.im/),etc.

**Comment by fython** [comment]
Scanning QR Code to download Android app is a bad habit. You should search app in Play Store or download it in GitHub Release.

I don't think it convenient to download apk by QQ/WeChat/etc's scanner. Sometimes you need to click twice or more times for opening external browser.

**Comment by jianhui1012** [comment]
i want to express broaden the channels to approach to the interest of people,because of different people have different needs.By the QR code only add one new way, don't influence with by other ways.
