### ISSUE TITLE
[Bug] 存在包裹单号导致闪退

### ISSUE THREAD

**Issue by bitkwan** [fython/PackageTracker#46]
一添加，就打不开App了。
每次添加完了就会闪退，必须要清空应用数据才能打开。
但是再次添加又会触发无线闪退。

单号 9274896343889137673298 
而且识别成了USPS，应该是UPS

**Comment by vadonmo** [comment]
你手机问题，我添加了没问题

**Comment by fython** [comment]
@bitkwan 请问最新版还有没有这个现象

**Comment by bitkwan** [comment]
@coderfox 依旧会…

**Comment by fython** [comment]
最新版中测试这个问题已经解决了。
