### ISSUE TITLE
打开就crash闪退（日志在下面）

### ISSUE THREAD

**Issue by naloder** [fython/PackageTracker#49]
11-03 17:01:31.417  9879  9879 E AndroidRuntime: FATAL EXCEPTION: main
11-03 17:01:31.417  9879  9879 E AndroidRuntime: Process: info.papdt.express.helper, PID: 9879
11-03 17:01:31.417  9879  9879 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{info.papdt.express.helper/info.papdt.express.helper.ui.MainActivity}: java.lang.NullPointerException: Attempt to get length of null array
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2695)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2775)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread.access$900(ActivityThread.java:189)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1599)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:111)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:194)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5883)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1119)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:885)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at info.papdt.express.helper.ui.common.AbsActivity.onCreate(AbsActivity.kt:32)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at info.papdt.express.helper.ui.MainActivity.onCreate(MainActivity.kt:60)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6200)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1117)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2642)
11-03 17:01:31.417  9879  9879 E AndroidRuntime: 	... 11 more

**Comment by fython** [comment]
了解，下个版本会修复这个问题。另外，请问机器有没有安装 FontProvider 应用？
