### ISSUE TITLE
能否支持苏宁快递的查询？

### ISSUE THREAD

**Issue by CeresCheng** [fython/PackageTracker#50]
天猫部分快递是由苏宁快递运送的，
但是水表助手无法识别苏宁快递的单号，手动新增包裹提示的快递公司是 加拿大(Canada Post)

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Galaxy S7 发送_

**Comment by JackyRen** [comment]
+1
提供一个示例，
运单编号：SN0030003615912300
查询页面：http://wuliu.suning.com/slp/home/toLogisticsDetail.htm

**Comment by iVanilla** [comment]
我的提示是万象物流

**Comment by fython** [comment]
@CeresCheng @JackyRen @iVanilla 自动识别由快递 100 API 完成，如出现问题可以尝试手动选择快递公司。很抱歉我无法改善识别效果。

**Comment by iVanilla** [comment]
貌似百毒的 API 可以查询了
