### ISSUE TITLE
快递跟踪信息严重延迟

### ISSUE THREAD

**Issue by 1kevin335200** [fython/PackageTracker#51]
其他快递不知道，就顺丰而说，目前的体验是官网、淘宝均显示已经到目的地城市了助手里面显示还是毫无跟踪信息
用的API有点问题？

**Comment by 1kevin335200** [comment]
![screenshot from 2018-01-07 14-40-40](https://user-images.githubusercontent.com/15524267/34650036-5e667b64-f3ba-11e7-98af-9b8f89052b4d.png)
![screenshot_20180107-145206](https://user-images.githubusercontent.com/15524267/34650044-6c51320a-f3ba-11e7-8835-843725f604d7.png)

**Comment by fython** [comment]
很抱歉，这段时间以来我们用的快递 100 API 似乎查不了顺丰，暂时没法更换 API……我过一段时间才能修复

**Comment by iVanilla** [comment]
目前主流快递好像只有顺丰有这个问题
