### ISSUE TITLE
能否添加分享到水表助手的功能？

### ISSUE THREAD

**Issue by ghost** [fython/PackageTracker#65]
比如我用 fooView 的 OCR 功能识别出了运单号，希望直接分享到水表助手来添加包裹信息，不需要先复制再手动添加。

**Comment by iVanilla** [comment]
@fython 这个是在选择文字的情况下出现的，不过如果我在支付宝账单详情这里去查看的话，似乎并不能直接复制 (当然我也可以使用 Universal Copy 之类的方式去复制，但是没有 fooView 方便)，当然希望直接点击分享到水表助手来添加包裹信息。

**Comment by fython** [comment]
十分感谢您的反馈和支持~ 很抱歉我们多番考虑过后这个功能将不会加入。
