### ISSUE TITLE
快递100 接口返回“查无结果”

### ISSUE THREAD

**Issue by Coolkkmeat** [fython/PackageTracker#70]
如题，我分析了一下接口，发现好像是需要验证一个叫做WWWID的cookies。

> `https://cache.kuaidi100.com/index.html?option=add&gCompanyCode=快递公司代号&gKuaidiNumber=快递单号&gIsCheck=0`
这个URL用来Set-Cookie WWWID。

**Comment by zzheng2005** [comment]
请问一下你是怎么解决的啊？ 我每次都返回 查无结果

**Comment by Coolkkmeat** [comment]
> 请问一下你是怎么解决的啊？ 我每次都返回 查无结果

当时有验证cookie，现在不知道了，我换成其他第三方接口了

**Comment by zzheng2005** [comment]
哦  有比较简单的吗？呵呵
发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Coolkk <notifications@github.com>
发送时间: 2019年5月21日 21:23
收件人: fython/PackageTracker <PackageTracker@noreply.github.com>
抄送: zzheng2005 <zzheng2005@gmail.com>, Comment <comment@noreply.github.com>
主题: 回复：[fython/PackageTracker] 快递100 接口返回“查无结果” (#70)



 
请问一下你是怎么解决的啊？ 我每次都返回 查无结果
  
当时有验证cookie，现在不知道了，我换成其他第三方接口了

**Comment by Coolkkmeat** [comment]
> 哦 有比较简单的吗？呵呵 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Coolkk <notifications@github.com> 发送时间: 2019年5月21日 21:23 收件人: fython/PackageTracker <PackageTracker@noreply.github.com> 抄送: zzheng2005 <zzheng2005@gmail.com>, Comment <comment@noreply.github.com> 主题: 回复：[fython/PackageTracker] 快递100 接口返回“查无结果” (#70) 请问一下你是怎么解决的啊？ 我每次都返回 查无结果 当时有验证cookie，现在不知道了，我换成其他第三方接口了 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

伙伴数据资源、快宝开放平台 啥的，虽然不是很全，至少稳定
